const actionTypes = {
  SORT_ORDER_CHANGED: 'SORT_ORDER_CHANGED',
  PREFERENCES: 'PREFERENCES',
  FETCH_HOTELS_REQUEST: 'FETCH_HOTELS_REQUEST',
  FETCH_HOTELS_SUCCESS: 'FETCH_HOTELS_SUCCESS'
};

export default actionTypes;